# Generated by Django 4.0.6 on 2022-09-19 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jasa', models.CharField(max_length=240, null=True)),
                ('harga', models.IntegerField()),
            ],
            options={
                'db_table': 'produk',
            },
        ),
        migrations.CreateModel(
            name='Konsumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('alamat', models.CharField(max_length=240)),
                ('hp', models.IntegerField(max_length=13)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konsumen.produk', verbose_name='produk_id')),
            ],
            options={
                'db_table': 'konsumen',
            },
        ),
    ]
