# Generated by Django 4.0.6 on 2022-09-20 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konsumen', '0003_alter_konsumen_hp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konsumen',
            name='produk',
        ),
    ]
