# Generated by Django 4.0.6 on 2022-09-20 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konsumen', '0004_remove_konsumen_produk'),
    ]

    operations = [
        migrations.AddField(
            model_name='konsumen',
            name='produk',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='konsumen.produk', verbose_name='produk_id'),
            preserve_default=False,
        ),
    ]
