# Generated by Django 4.0.6 on 2022-09-20 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konsumen', '0005_konsumen_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konsumen',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konsumen.produk'),
        ),
    ]
