# Generated by Django 4.0.6 on 2022-09-25 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konsumen', '0008_konsumen_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konsumen',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konsumen.produk', verbose_name='produk_id'),
        ),
    ]
