# Generated by Django 4.0.6 on 2022-09-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konsumen', '0012_alter_konsumen_produk'),
    ]

    operations = [
        migrations.AddField(
            model_name='konsumen',
            name='bukti',
            field=models.ImageField(default='False', null='True', upload_to=''),
            preserve_default='True',
        ),
    ]
