# Generated by Django 4.0.6 on 2022-09-27 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konsumen', '0013_konsumen_bukti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konsumen',
            name='bukti',
        ),
    ]
